TASK-50543:New UI for settings page
Meeds-io/social pull request #1043
Opened 2021-10-25 10:45 UTC by GouadriaHanen

2021-10-25 15:43 UTC, plamarque commented on webapp/portlet/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <name>UserSettingMenu</name>
```suggestion
    <name>UserSettingsMenu</name>
```

2021-10-25 15:43 UTC, plamarque commented on webapp/portlet/src/main/webapp/WEB-INF/gatein-resources.xml
> +        <path>js/userSettingMenu.bundle.js</path>
```suggestion
        <path>js/userSettingsMenu.bundle.js</path>
```

2021-10-25 15:43 UTC, plamarque commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/userSettingMenu.jsp
> +      require(['PORTLET/social-portlet/UserSettingMenu'], app => app.init());
```suggestion
      require(['PORTLET/social-portlet/UserSettingsMenu'], app => app.init());
```

2021-10-25 15:43 UTC, plamarque commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +    <portlet-name>UserSettingMenu</portlet-name>
```suggestion
    <portlet-name>UserSettingsMenu</portlet-name>
```

2021-10-25 15:44 UTC, plamarque commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +      <value>/WEB-INF/jsp/userSettingMenu.jsp</value>
```suggestion
      <value>/WEB-INF/jsp/userSettingsMenu.jsp</value>
```

2021-10-25 15:44 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/components/UserSettingMenu.vue
> +  <v-app id="UserSettingMenu">
```suggestion
  <v-app id="UserSettingsMenu">
```

2021-10-25 15:44 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/initComponents.js
> +import UserSettingMenu from './components/UserSettingMenu.vue';
```suggestion
import UserSettingsMenu from './components/UserSettingsMenu.vue';
```

2021-10-25 15:44 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/initComponents.js
> +  'user-setting-menu': UserSettingMenu,
```suggestion
  'user-settings-menu': UserSettingsMenu,
```

2021-10-25 15:45 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/main.js
> +  const components = extensionRegistry.loadComponents('UserSettingMenu');
```suggestion
  const components = extensionRegistry.loadComponents('UserSettingsMenu');
```

2021-10-25 15:45 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/main.js
> +const appId = 'UserSettingMenu';
```suggestion
const appId = 'UserSettingsMenu';
```

2021-10-25 15:45 UTC, plamarque commented on webapp/portlet/src/main/webapp/vue-apps/user-setting-menu/main.js
> +        template: '<user-setting-menu/>',
```suggestion
        template: '<user-settings-menu/>',
```

2021-10-25 15:45 UTC, plamarque commented on webapp/portlet/webpack.common.js
> +    userSettingMenu: './src/main/webapp/vue-apps/user-setting-menu/main.js',
```suggestion
    userSettingsMenu: './src/main/webapp/vue-apps/user-settings-menu/main.js',
```

2021-10-25 15:46 UTC, plamarque requested changes
please use plural everywhere for settings : UserSettingsMenu

2021-10-26 11:35 UTC, GouadriaHanen commented
TASK closed

2021-10-26 11:35 UTC, closed without merging