Task-50930 : Add metadata news targets get method
Meeds-io/social pull request #1072
Opened 2021-11-12 15:24 UTC by ahmadmido

Add metadata news targets get method.

2021-11-12 15:32 UTC, azayati requested changes
see review

2021-11-12 15:32 UTC, azayati commented on component/api/src/main/java/org/exoplatform/social/metadata/MetadataService.java
> +  List<Metadata> getMetadata();
no need of this change, Metadata API is complete, you should use the existing methods

2021-11-16 14:37 UTC, ahmadmido commented on component/api/src/main/java/org/exoplatform/social/metadata/MetadataService.java
> +  List<Metadata> getMetadata();
> methods

We need all metadata information as discussed with @hassenelkamel-exo, so we need a new implementation that gives us a list of metadata.

2021-11-17 09:05 UTC, azayati requested changes
se review

2021-11-17 09:05 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +    return Collections.unmodifiableList(metadataList);
getMetadata should retrieve from the database using the metadataDAO.

2021-11-17 11:15 UTC, azayati requested changes
see review

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/MetadataDAO.java
> +  public List<MetadataEntity> getMetadataByType(long type) {
```suggestion
  public List<MetadataEntity> getMetadatasByType(long type) {
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/MetadataDAO.java
> +    TypedQuery<MetadataEntity> query = getEntityManager().createNamedQuery("SocMetadataEntity.getMetadataByType",
```suggestion
    TypedQuery<MetadataEntity> query = getEntityManager().createNamedQuery("SocMetadataEntity.getMetadatasByType",
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/entity/MetadataEntity.java
> +          name = "SocMetadataEntity.getMetadataByType",
```suggestion
          name = "SocMetadataEntity.getMetadatasByType",
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/MetadataServiceImpl.java
> +  public List<Metadata> getMetadataByType(long type) {
```suggestion
  public List<Metadata> getMetadatasByType(long type) {
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/MetadataServiceImpl.java
> +    return metadataStorage.getMetadataByType(type);
```suggestion
    return metadataStorage.getMetadatasByType(type);
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +  public List<Metadata> getMetadataByType(long type) {
```suggestion
  public List<Metadata> getMetadatasByType(long type) {
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +    List<MetadataEntity> metadataEntityList = metadataDAO.getMetadataByType(type);
```suggestion
    List<MetadataEntity> metadataEntities = metadataDAO.getMetadatasByType(type);
```

2021-11-17 11:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +    return metadataEntityList.stream().map(this::fromEntity).collect(Collectors.toList());
```suggestion
    return metadataEntities.stream().map(this::fromEntity).collect(Collectors.toList());
```

2021-11-17 14:46 UTC, azayati approved these changes
LGTM after QA validation

2021-11-17 15:25 UTC, azayati requested changes
see review

2021-11-17 15:25 UTC, azayati commented on component/api/src/main/java/org/exoplatform/social/metadata/MetadataService.java
> +  List<Metadata> getMetadatasByType(long type);
we should use name as parameter
we should use offset/limit and use limit=100 to get the whole list

2021-11-17 17:09 UTC, azayati requested changes
We don't need to add a new method right now as discussed with @ahmadmido, we will use the existing methods. So this PR to be removed, the branch to be kept if needed later.

2021-11-18 08:58 UTC, azayati requested changes
see review

2021-11-18 08:58 UTC, azayati commented on component/api/src/main/java/org/exoplatform/social/metadata/MetadataService.java
> +  List<Metadata> getMetadatas(String name, long limit);
```suggestion
  List<Metadata> getMetadatas(String metadataTypeName, long limit);
```

2021-11-18 08:58 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/MetadataServiceImpl.java
> +  public List<Metadata> getMetadatas(String name, long limit) {
```suggestion
  public List<Metadata> getMetadatas(String metadataTypeName, long limit) {
```

2021-11-18 08:58 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/MetadataServiceImpl.java
> +    return metadataStorage.getMetadatas(name, limit);
```suggestion
    return metadataStorage.getMetadatas(metadataTypeName, limit);
```

2021-11-18 08:58 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +  public List<Metadata> getMetadatas(String name, long limit) {
```suggestion
  public List<Metadata> getMetadatas(String metadataTypeName, long limit) {
```

2021-11-18 08:58 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +    MetadataType metadataType = getMetadataType(name);
```suggestion
    MetadataType metadataType = getMetadataType(metadataTypeName);
```

2021-11-18 08:58 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/metadata/storage/MetadataStorage.java
> +      throw new IllegalStateException("Metadata type with name " + name + " isn't defined");
```suggestion
      throw new IllegalStateException("Metadata type with name " + metadataTypeName+ " isn't defined");
```

2021-11-18 09:20 UTC, azayati submitted a review, later dismissed
LGTM after QA validation

2021-11-18 14:39 UTC, azayati approved these changes
LGTM

2021-11-18 14:47 UTC, merged