Feature EE 6.0 : Hide composer on Stream page
Meeds-io/social pull request #115
Opened 2020-06-03 16:33 UTC by Rdidmohamedelhadi

2020-06-03 16:39 UTC, plamarque requested changes
property name does not clearly reflect that it is the composer on stream page that is configured.

Also, it should be false by default on eXo and true by default on Meeds.  This PR only deals with the case of eXo.

Finally, I think the property should be present and documented with a comment inside the build-in exo.properties.

In current state this PR essentially creates an invisible property. It should be exposed.

2020-06-03 16:44 UTC, Rdidmohamedelhadi commented
> property name does not clearly reflect that it is the composer on stream page that is configured.
> 
> Also, it should be false by default on eXo and true by default on Meeds. This PR only deals with the case of eXo.
> 
> Finally, I think the property should be present and documented with a comment inside the build-in exo.properties.
> 
> In current state this PR essentially creates an invisible property. It should be exposed.



> property name does not clearly reflect that it is the composer on stream page that is configured.
> 
> Also, it should be false by default on eXo and true by default on Meeds. This PR only deals with the case of eXo.
> 
> Finally, I think the property should be present and documented with a comment inside the build-in exo.properties.
> 
> In current state this PR essentially creates an invisible property. It should be exposed.



> property name does not clearly reflect that it is the composer on stream page that is configured.
> 
> Also, it should be false by default on eXo and true by default on Meeds. This PR only deals with the case of eXo.
> 
> Finally, I think the property should be present and documented with a comment inside the build-in exo.properties.
> 
> In current state this PR essentially creates an invisible property. It should be exposed.

ok !! well noted

2020-06-04 13:45 UTC, mzorai commented
> property name does not clearly reflect that it is the composer on stream page that is configured.
> 

I proposed this property name  exo.social.composer.stream.hidden
true: to disable displaying the composer in the stream
false: to enable displaying the composer in the stream

2020-06-04 13:57 UTC, azayati requested changes
See review

2020-06-04 13:57 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/composer/UIComposer.gtmpl
> +  def isEnable = PropertyManager.getProperty("exo.composer.enable");
```suggestion
  def isMainStreamComposerEnabled= PropertyManager.getProperty("exo.config.mainStreamComposer.enabled");
```

2020-06-04 13:57 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/composer/UIComposer.gtmpl
> +  if( isEnable == null ){
To be deleted

2020-06-04 13:57 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/composer/UIComposer.gtmpl
> +  if(featureService.isActiveFeature("new-composer") && isEnable) {
```suggestion
  if(featureService.isActiveFeature("new-composer")) {
  if (isMainStreamComposerEnabled) {
```

2020-06-04 13:59 UTC, azayati commented
> > property name does not clearly reflect that it is the composer on stream page that is configured.
> 
> I proposed this property name exo.social.composer.stream.hidden
> true: to disable displaying the composer in the stream
> false: to enable displaying the composer in the stream

2020-06-04 14:04 UTC, mzorai commented
> > > property name does not clearly reflect that it is the composer on stream page that is configured.
> > 
> > 
> > I proposed this property name exo.social.composer.stream.hidden
> > true: to disable displaying the composer in the stream
> > false: to enable displaying the composer in the stream
> 
> @mzorai See with archi, we will use this name for the prooperty exo.config.mainStreamComposer.enabled

OK so it should be true to enable and false to disable

2020-06-05 08:41 UTC, azayati approved these changes
LGTM

2020-06-05 08:41 UTC, merged