TASK-49429 : Tags added suggested in unified search
Meeds-io/social pull request #1274
Opened 2022-01-31 16:10 UTC by nidhalnidhal

suggest only the 5 last added tags when searching for content in the unified search based on tags .

2022-02-01 08:53 UTC, AzmiTouil requested changes

2022-02-01 08:53 UTC, AzmiTouil commented on component/core/src/main/java/org/exoplatform/social/core/metadata/tag/TagServiceImpl.java
> +      Collections.reverse(metadataNames);
reformat code please!

2022-02-02 12:24 UTC, SaraBoutej approved these changes

2022-02-02 13:48 UTC, AzmiTouil requested changes

2022-02-02 13:48 UTC, AzmiTouil commented on component/api/src/main/java/org/exoplatform/social/metadata/MetadataService.java
> +   * {@link MetadataType} and {@link Set} of audience {@link Identity} ids and
```suggestion
   * {@link MetadataType} and {@link Set} of audience {@link Identity} ids
```

2022-02-02 13:48 UTC, AzmiTouil commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/entity/MetadataEntity.java
> +                  name = "SocMetadataEntity.findMetadataNameByUser",
```suggestion
                  name = "SocMetadataEntity.findMetadataNameByUserAndQuery",
```

2022-02-02 13:48 UTC, AzmiTouil commented on component/core/src/main/java/org/exoplatform/social/core/metadata/MetadataServiceImpl.java
> +  public List<String> findMetadataNamesByUser(String term, String metadataTypeName, Set<Long> audienceIds, long creatorId, long limit) {
```suggestion
  public List<String> findMetadataNamesByUserAndQuery(String term, String metadataTypeName, Set<Long> audienceIds, long creatorId, long limit) {
```

2022-02-02 13:48 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/search/components/SearchTagList.vue
> +      this.searching = this.query.length > 0 ? true : false;
```suggestion
      this.searching = this.query.length > 0 || false;
```

2022-02-02 14:41 UTC, AzmiTouil approved these changes

2022-02-02 14:54 UTC, merged