TASK-49429 : Track the number of times tags are added (Rework)
Meeds-io/social pull request #1288
Opened 2022-02-07 14:08 UTC by nidhalnidhal

Track the number of time tags are added

2022-02-07 14:12 UTC, ghost commented
### CodeSee Review Map:
[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/Meeds-io/social/1288/d4e1c8f9/844e6cff6c7355fe166adf793f91443f6d004a31.svg)](https://app.codesee.io/r/reviews?pr=1288&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

Review [in an interactive map](https://app.codesee.io/r/reviews?pr=1288&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2022-02-09 10:53 UTC, AzmiTouil approved these changes

2022-02-09 10:58 UTC, AzmiTouil requested changes

2022-02-09 10:58 UTC, AzmiTouil commented on component/core/src/main/java/org/exoplatform/social/core/listeners/ActivityTagMetadataListener.java
> +      listenerService.broadcast(TAG_ADDED_EVENT,activity,tagNames);
the **tagNames** in this case will contain all activity tags, even the old ones ? or just the new tags added

2022-02-10 15:43 UTC, AzmiTouil approved these changes

2022-02-10 16:26 UTC, merged