Task-54468: User exo-user component for kudos activity and comment
Meeds-io/social pull request #1324
Opened 2022-02-21 16:48 UTC by SaraBoutej

2022-02-21 20:05 UTC, AzmiTouil requested changes

2022-02-21 20:05 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/activity-reactions/components/ActivityLikerItem.vue
> +      :extra-class="'pl-3 pt-2 pb-1'"
```suggestion
      extra-class="pl-3 pt-2 pb-1"
```

2022-02-21 20:05 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/activity-stream/components/activity/content/ActivityLink.vue
> +            :extra-class="'ms-2'"
```suggestion
            extra-class="ms-2"
```

2022-02-22 08:02 UTC, SaraBoutej commented on webapp/portlet/src/main/webapp/vue-apps/activity-reactions/components/ActivityLikerItem.vue
> +      :extra-class="'pl-3 pt-2 pb-1'"
Done!

2022-02-22 08:03 UTC, SaraBoutej commented on webapp/portlet/src/main/webapp/vue-apps/activity-stream/components/activity/content/ActivityLink.vue
> +            :extra-class="'ms-2'"
Done!

2022-02-22 08:34 UTC, AzmiTouil approved these changes

2022-02-22 08:35 UTC, merged