Task-56509 :added the mainApplicationName property when creating an activity-stream
Meeds-io/social pull request #1435
Opened 2022-04-26 14:49 UTC by Amine0008

added the mainApplicationName property when creating an activity-stream so we can track the use of exo's main applications in mobile statistics

2022-04-26 14:52 UTC, ghost commented
### CodeSee Review Map:
[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/Meeds-io/social/1435/3d270dbd/e0d1dbd70972710bae9680b92eb7eefcd05c4d0a.svg)](https://app.codesee.io/r/reviews?pr=1435&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

Review [in an interactive map](https://app.codesee.io/r/reviews?pr=1435&src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2FMeeds-io%2Fsocial)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2022-04-26 16:31 UTC, boubaker commented on webapp/portlet/src/main/webapp/vue-apps/activity-stream/main.js
> +eXo.env.portal.mainApplicationName = 'Social';
```suggestion
eXo.env.portal.mainApplicationName = 'activityStream';
```

It's better to add a name that you can add in i18N File and that is significative. To know if you want to use `social` (one single module name for all social apps) or `activityStream` + `peopleList` + `spaceList` + (moduleName per Application) ... could you please ask @Samuel-Renault-eXo or Morgan

2022-05-04 08:40 UTC, ahamdi commented
@Amine0008 Could you check the review ?

2022-05-06 16:20 UTC, ahamdi approved these changes

2022-05-12 16:06 UTC, azayati requested changes
Please update the title in order to use a simple verb like Add not added. And for the description try to explain the problem and how it is fixed.

2022-05-12 16:41 UTC, boubaker commented
The issue has been postponed to post TC, thus I close the issue to be worked in dedicated FT.

2022-05-12 16:41 UTC, closed without merging