Task-56602: Copy of [AUTH][UXFT] TopBar_BUG01.2: Favorite icon alignment
Meeds-io/social pull request #1436
Opened 2022-04-26 15:03 UTC by sofyenne

problem: bad alignement of icon favorite

2022-04-26 15:53 UTC, boubaker requested changes
Please see best practices for commit titles https://developer.exoplatform.org/

2022-04-27 14:42 UTC, ahamdi submitted a review, later dismissed

2022-05-05 09:01 UTC, boubaker commented on webapp/portlet/src/main/webapp/vue-apps/favorites-list-top-bar/components/ExoTopBarFavorites.vue
> +          <v-icon size="21" class="pt-7 mb-10 mt-2" >fa-star</v-icon>
```suggestion
          <v-icon size="22" class="pb-1" >fa-star</v-icon>
```

2022-05-05 10:18 UTC, sofyenne reviewed
done !

2022-05-05 16:30 UTC, boubaker approved these changes

2022-05-05 16:52 UTC, merged