Task-56986: Prevent updating activity stream when posting hidden activities
Meeds-io/social pull request #1455
Opened 2022-05-10 14:12 UTC by hchaabene

Prior to this fix, when posting a hidden activity, a blue flag "new post" is displayed on the space activity stream.
After this fix, we avoid displaying the flag when posting a hidden activity

2022-05-10 15:07 UTC, azayati requested changes
IMHO, Since it is a general problem of any type of hidden activity, the title and the description should be generic to be not news activity related only (Also to not mention an exo addon on a meeds codebase)

2022-05-10 15:27 UTC, boubaker approved these changes

2022-05-10 17:10 UTC, azayati approved these changes
LGTM

2022-05-10 17:10 UTC, merged

2022-05-11 13:10 UTC, azayati commented
@hchaabene don't forget to take into account the update of the title and the description according to our last discussion