Feature/news: Update activity composer extension
Meeds-io/social pull request #164
Opened 2020-07-02 11:36 UTC by aelbenney

In order to make it possible for plugins to make rest calls, modifications,.. before self init, we added an event listener `activity-composer-extension-updated` to update the composer extension whenever needed.

2020-07-02 11:47 UTC, boubaker commented on webapp/vue-portlet/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please pay attention, this file is not needed anymore

2020-07-03 17:41 UTC, ahamdi approved these changes
LGTM

2020-07-03 17:42 UTC, ahamdi requested changes
Please open a task on maintenance.

2020-07-06 10:55 UTC, ahamdi approved these changes
LGTM

2020-07-06 10:55 UTC, merged