MEED-353: Add Favorite action in the space topbar popover
Meeds-io/social pull request #1765
Opened 2022-09-01 09:36 UTC by SaraBoutej

2022-09-01 11:22 UTC, boubaker commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/bannerLogo.jsp
> +    space = spaceObject;
redundant IMO
```suggestion
```

2022-09-01 11:23 UTC, boubaker commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/bannerLogo.jsp
> +    space: `<%=spaceObject%>`,
You need here the space REST object representation and not the space Service Layer DTO. BTW, you may need just the 'isFavorite' attribute only

2022-09-02 09:22 UTC, AzmiTouil requested changes

2022-09-02 09:22 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +      return this.spaceId;
no need to compute this IMO

2022-09-02 09:22 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/bannerLogo.jsp
> +    isMember: `<%=isMember%>`,
Can non member access to space logo banner? I think it's an unnecessary check at this stage

2022-09-02 09:43 UTC, AzmiTouil requested changes

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +    this.id = this.spaceId;
```suggestion
```

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +    id: ''
```suggestion
```

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +    :space-id="id"
```suggestion
    :space-id="spaceId"
```

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +      document.dispatchEvent(new CustomEvent('space-favorite-removed', {detail: this.id}));
```suggestion
      document.dispatchEvent(new CustomEvent('space-favorite-removed', {detail: this.spaceId}));
```

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/spaces-list/components/ExoSpaceFavoriteAction.vue
> +      document.dispatchEvent(new CustomEvent('space-favorite-added', {detail: this.id}));
```suggestion
      document.dispatchEvent(new CustomEvent('space-favorite-added', {detail: this.spaceId}));
```

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/bannerLogo.jsp
> +
To move in **else** block please

2022-09-02 09:43 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/bannerLogo.jsp
> +  Identity userIdentity = identityManager.getOrCreateUserIdentity(authenticatedUser);
To move in **else** block please

2022-09-02 10:05 UTC, AzmiTouil approved these changes

2022-09-02 10:10 UTC, merged