MEED-419: Add bookmark/unbookmark space in the left navigation spaces
Meeds-io/social pull request #1792
Opened 2022-09-12 13:19 UTC by SaraBoutej

This Changes allow to bookmark/unbookmark a space from the last visited spaces in the left navigation drawer.

2022-09-12 14:11 UTC, AzmiTouil requested changes

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   * Gets if the space is bookmarked or not.
```suggestion
   * Check whether the space is favorite or not.
```

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   * Sets if the space is bookmarked or not.
```suggestion
   * Sets the checks if is favorite space.
```

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +import org.exoplatform.social.core.identity.model.Identity;
useless imports!

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +import org.exoplatform.social.metadata.favorite.model.Favorite;
useless imports!

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   */
```suggestion
  /**
   * Gets the space id .
   *
   * @return the space id
   */
```

2022-09-12 14:11 UTC, AzmiTouil commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +    this.isFavorite = isFavorite;
Should be retrieved from space item IMO.

2022-09-12 14:13 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +    this.isFavorite = isFavorite;
We don't have this information in the space entity!

2022-09-12 14:17 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   * Gets if the space is bookmarked or not.
done!

2022-09-12 14:17 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   * Sets if the space is bookmarked or not.
Done!

2022-09-12 14:17 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +import org.exoplatform.social.core.identity.model.Identity;
Done!

2022-09-12 14:18 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +import org.exoplatform.social.metadata.favorite.model.Favorite;
Removed!

2022-09-12 14:18 UTC, SaraBoutej commented on component/service/src/main/java/org/exoplatform/social/service/rest/SpaceRest.java
> +   */
fixed!

2022-09-13 14:42 UTC, AzmiTouil approved these changes

2022-09-13 14:44 UTC, merged