feat: OVERVIEW PAGE add overview banner - MEED-551 - Meeds-io/MIPs#10
Meeds-io/social pull request #1885
Opened 2022-10-16 23:46 UTC by ArfaouiMohamedAmine

this change is going to add a 1 year (31536000 seconds) cached banner for the overview page based on overview-banner html file and implemented in overview-banner portlet

2022-10-18 13:21 UTC, AzmiTouil requested changes

2022-10-18 13:21 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/html/overview-banner.html
> +</style>
To use helper classes + Vuetify classes instead

2022-10-18 13:21 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/html/overview-banner.html
> +<html lang="en">
```suggestion
```

2022-10-18 13:21 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/html/overview-banner.html
> +</html>
```suggestion
```

2022-10-18 13:21 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/html/overview-banner.html
> +                Let's see what to do today
should use the portlet preference

2022-10-21 17:03 UTC, AzmiTouil requested changes

2022-10-21 17:03 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +		if (bannerUrl == null) {
IMO, it can't be null

2022-10-21 17:03 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +	if (bannerTitle == null) {
if null, we should display a placeholder instead

2022-10-21 17:03 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +	if (bannerCaption == null) {
if null, we should display a placeholder instead

2022-10-21 17:03 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +    </portlet-preferences>
we need to set init values?

2022-10-21 17:03 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +    caption = bundle.getString(bannerCaption.toString());
reformat code please!

2022-10-24 08:36 UTC, ArfaouiMohamedAmine commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +    </portlet-preferences>
init values are no need ! already omitted!

2022-10-24 08:37 UTC, ArfaouiMohamedAmine commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +	if (bannerCaption == null) {
done !

2022-10-24 08:37 UTC, ArfaouiMohamedAmine commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +	if (bannerTitle == null) {
done !

2022-10-24 08:37 UTC, ArfaouiMohamedAmine commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/overviewBanner.jsp
> +		if (bannerUrl == null) {
kept a placeholder for the urlBanner in case of the url provided by the page is no good

2022-10-25 10:10 UTC, AzmiTouil approved these changes

2022-10-25 10:11 UTC, merged