feat : reorganize application registry list - EXO-61480 - Meeds-io/MPIs#37
Meeds-io/social pull request #2092
Opened 2023-01-03 14:25 UTC by sofyenne

this change going to add `External Spaces List Portlet , SpaceMenuPortle and WhoIsOnLinePortlet ` under the Tools  application registry ctaegory.

2023-01-05 15:59 UTC, azayati requested changes

2023-01-05 15:59 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/application-registry-configuration.xml
> +                  </value>
separate tags

2023-01-05 16:00 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-01-05 18:12 UTC, sofyenne commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/application-registry-configuration.xml
> +                  </value>
done !

2023-01-06 10:09 UTC, azayati approved these changes
LGTM

2023-01-06 10:11 UTC, merged