feat: Change some UI of the menu members card when using a mobile - MEED-1518 - Meeds-io/meeds#549
Meeds-io/social pull request #2188
Opened 2023-01-19 11:22 UTC by MayTekayaa

This fix will change some UI of the menu members card when using a mobile.

2023-01-19 15:57 UTC, AzmiTouil requested changes

2023-01-19 15:57 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +          fa-ellipsis-v
```suggestion
          fas fa-ellipsis-v
```

2023-01-19 15:57 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +          <v-sheet class="text-center" height="100px">
```suggestion
          <v-sheet class="text-center" height="100">
```

2023-01-19 15:57 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +                v-if="user.relationshipStatus === 'CONFIRMED'"
To add in computed, please!

2023-01-19 15:57 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +                v-else-if="user.relationshipStatus === 'INCOMING'">
To add in computed, please!

2023-01-19 15:57 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +                  <v-icon class="mx-4" size="16">fa-plus-circle</v-icon>
```suggestion
                  <v-icon class="mx-4" size="16">fas fa-plus-circle</v-icon>
```

2023-01-20 08:51 UTC, MayTekayaa commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +          fa-ellipsis-v
done!

2023-01-20 08:51 UTC, MayTekayaa commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +          <v-sheet class="text-center" height="100px">
done!

2023-01-20 08:51 UTC, MayTekayaa commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +                v-if="user.relationshipStatus === 'CONFIRMED'"
done!

2023-01-20 08:51 UTC, MayTekayaa commented on webapp/portlet/src/main/webapp/vue-apps/people-list/components/PeopleCardFront.vue
> +                  <v-icon class="mx-4" size="16">fa-plus-circle</v-icon>
done!

2023-01-20 09:08 UTC, AzmiTouil approved these changes

2023-01-20 09:45 UTC, merged