Maint-26764: Reactions Labels( Reply and kudos) not colored in blue
Meeds-io/social pull request #229
Opened 2020-07-28 08:34 UTC by lbengayed

2020-07-28 12:56 UTC, ahamdi submitted a review, later dismissed
Why don't you use the reply class ? 
Shouldn't all labels of Reply link have the principal color for repluing to activity or a comment ?
cc @samehaidi

2020-07-28 14:13 UTC, lbengayed commented
> Why don't you use the reply class ?
> Shouldn't all labels of Reply link have the principal color for repluing to activity or a comment ?
> cc @samehaidi

i keep it like likelabel https://github.com/Meeds-io/social/blob/develop/extension/war/src/main/webapp/groovy/social/webui/activity/UIActivityCommentActions.gtmpl#L56 
, for that i don't use the reply class

2020-08-11 14:00 UTC, azayati requested changes
@lbengayed We should discuss about this PR

2020-08-11 14:00 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/activity/UIActivityCommentActions.gtmpl
> +        def replyCommentClass = "";
```suggestion
        def replyCommentClass = comment.parentCommentId !=null ? "reply" :  "replyComment";
```

2020-08-11 14:00 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/activity/UIActivityCommentActions.gtmpl
> +        if (comment.parentCommentId!=null) {
This can be removed, see above

2020-08-11 14:00 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/activity/UIActivityCommentActions.gtmpl
> +        def replyCommentClass = "";
Does this mean that only buttons of level 2 comments blocks should be colored with blue ? @mzorai

2020-08-11 18:05 UTC, azayati commented on extension/war/src/main/webapp/groovy/social/webui/activity/UIActivityCommentActions.gtmpl
>              <a id="CommentLink${comment.id}" data-activity="$comment.parentId" data-comment="$parentCommentId" data-sub-comment="$subCommentId" data-author-name="$authorName" data-author-fullname="$a
I think that the class should be applied here not below

2020-08-18 10:31 UTC, azayati submitted a review, later dismissed
LGTM

2020-08-18 10:34 UTC, azayati approved these changes
LGTM

2020-08-18 10:52 UTC, merged