fix: fix chat button in left menu second level drawer is not working - EXO-62231
Meeds-io/social pull request #2297
Opened 2023-02-09 07:40 UTC by IlhemEssaadi

Prior to this change, when we open the left menu and we click on the right arrow next to the name of the space to open the second level menu and we click on the chat button nothing happens because when we navigate on the pages outside spaces pages eXo.env.portal.spaceId=' ', Aftet this change, we get the right value of spaceId and afterwards we can open the chat drawer

2023-02-09 07:55 UTC, boubaker commented
Please change title and description to reflect the fix in context of Meeds only without eXo addons context and names.

2023-02-10 11:39 UTC, ahamdi submitted a review, later dismissed

2023-02-13 10:23 UTC, ahamdi requested changes
@IlhemEssaadi Could you update title & description ? this is a Meeds project and we should not mention consequent issues in eXo addons, but just current issues on Meeds !

2023-02-13 18:27 UTC, ahamdi approved these changes

2023-02-14 07:50 UTC, merged