fix : Work experience values are empty after migrating from 5 to 6.4 - EXO-63059 - Meeds-io/meeds#848
Meeds-io/social pull request #2461
Opened 2023-03-22 14:58 UTC by sofyenne

Before to this change when we migrating from 5.3 to 6.4 user work experience value were empty and a console error would appear stating an invalid Time error , The problem was that the start work experience was stored with the format 03/07/2023  and the getDateObjectFromString method would always return a new date assuming the provided string was an ISO string, causing an error before checking if the stored date contained "/".
 With this change, we will first check if the provided date contains "/", and then return the correct date value."

2023-03-22 18:37 UTC, ahamdi requested changes

2023-03-22 18:37 UTC, ahamdi commented on webapp/portlet/src/main/webapp/vue-apps/common/js/DateUtil.js
> +  } else if (String(value).indexOf('/') >= 0) {
Could you use the digits pattern used for storing the date in version 5.3 instead of checking on the SLASH character ?

2023-03-22 22:09 UTC, sofyenne commented on webapp/portlet/src/main/webapp/vue-apps/common/js/DateUtil.js
> +  } else if (String(value).indexOf('/') >= 0) {
done !

2023-03-23 08:13 UTC, sofyenne commented on webapp/portlet/src/main/webapp/vue-apps/common/js/DateUtil.js
> +  } else if (String(value).indexOf('/') >= 0) {
done !

2023-03-23 08:29 UTC, ahamdi approved these changes

2023-03-23 08:31 UTC, merged