fix: Remove the user  from the old group synchronized profile property groups - EX-64814 - Meeds-io/meeds#1052
Meeds-io/social pull request #2702
Opened 2023-08-03 14:49 UTC by sofyenne

Prior to this change, after editing a group-synchronized profile property, a new group was created, and the user continued to be displayed among the members of the old group
This change is going to remove the user from the old group synchronized profile property groups.

2023-08-07 14:01 UTC, ahamdi requested changes

2023-08-07 14:01 UTC, ahamdi commented on component/core/src/main/java/org/exoplatform/social/core/listeners/GroupSynchronizationSocialProfileListener.java
> +        removeUserFromExistingPropertyGroup(newPropertyNameGroup, user);
aren't you removing then adding the user to the same group  here ?

2023-08-07 14:15 UTC, sofyenne commented on component/core/src/main/java/org/exoplatform/social/core/listeners/GroupSynchronizationSocialProfileListener.java
> +        removeUserFromExistingPropertyGroup(newPropertyNameGroup, user);
We are removing the user from the existing child group, and then adding them to the newly created child group within the same larger (parent) group!

2023-08-08 12:01 UTC, ahamdi approved these changes

2023-08-08 12:26 UTC, merged