feat: Add a new Images portlet to display the portlet banner - EXO-65514
Meeds-io/social pull request #2720
Opened 2023-08-15 14:14 UTC by IlhemEssaadi

2023-08-17 10:50 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-08-17 15:54 UTC, azayati requested changes

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/webpack.common.js
> +    portletBanner: './src/main/webapp/vue-apps/portlet-banner/main.js'
```suggestion
    banner: './src/main/webapp/vue-apps/banner/main.js'
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/portletBannerService.js
> +  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/portletBanner?${params}`, {
```suggestion
  return fetch(`${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/banner?${params}`, {
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/portletBannerService.js
> +      throw new Error('Error when retrieving portlet banner');
```suggestion
      throw new Error('Error when retrieving banner');
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/portlet/portletBanner.jsp
> +	String bannerUrl = preferences.getValue("bannerUrl", "");
indentation

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/main.js
> +    `#${appId}`, 'Portlet Banner');
```suggestion
    `#${appId}`, 'Banner');
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/initComponents.js
> +  'portlet-banner': PortletBanner,
```suggestion
  'banner': Banner,
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/initComponents.js
> +import PortletBanner from './components/PortletBanner.vue';
```suggestion
import PortletBanner from './components/Banner.vue';
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/initComponents.js
> +import * as portletBannerService from './portletBannerService.js';
```suggestion
import * as bannerService from './bannerService.js';
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/initComponents.js
> +    value: portletBannerService,
```suggestion
  window.Object.defineProperty(Vue.prototype, '$bannerService', {
    value: bannerService,
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +                :title="$t('portletBanner.title.deleteBanner')"
```suggestion
                :title="$t('banner.title.deleteBanner')"
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +                id="portletBannerDeleteButton"
```suggestion
                id="bannerDeleteButton"
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +                id="portletBannerEditButton"
```suggestion
                id="bannerEditButton"
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +                :title="$t('portletBanner.title.ChangeBanner')"
```suggestion
                :title="$t('banner.title.ChangeBanner')"
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +        drawer-title="portletBanner.title.ChangeBanner"
```suggestion
        drawer-title="banner.title.ChangeBanner"
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      return this.bannerUrl && this.bannerUrl.includes('/portal/rest/v1/social/spaceTemplates/');
IMO We should define another default banner not default space banner, to be verified with PO

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      this.bannerUrl = `${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/spaceTemplates/communication/banner`;
IMO We should define another default banner not default space banner, to be verified with PO

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +    getPortletBanner(uploadId) {
```suggestion
    getBanner(uploadId) {
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      return this.$portletBannerService.getPortletBanner(uploadId)
```suggestion
      return this.$bannerService.getBanner(uploadId)
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      return this.getPortletBanner(uploadId).
```suggestion
      return this.getBanner(uploadId).
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      this.bannerUrl = `${eXo.env.portal.context}/${eXo.env.portal.rest}/v1/social/spaceTemplates/communication/banner`;
IMO We should define another default banner not default space banner, to be verified with PO

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      this.$nextTick().then (() => this.$root.$emit('alert-message', this.$t('portletBanner.title.BannerDeleted'), 'success'));
```suggestion
      this.$nextTick().then (() => this.$root.$emit('alert-message', this.$t('banner.title.BannerDeleted'), 'success'));
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/components/PortletBanner.vue
> +      this.$portletBannerService.saveSettings(this.saveSettingsURL ,{
```suggestion
      this.$bannerService.saveSettings(this.saveSettingsURL ,{
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +    <portlet-class>org.exoplatform.social.portlet.ImagesPortlet</portlet-class>
```suggestion
    <portlet-name>BannerPortlet</portlet-name>
    <display-name>Banner Portlet</display-name>
    <portlet-class>org.exoplatform.social.portlet.BannerPortlet</portlet-class>
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +      <value>/WEB-INF/jsp/portlet/portletBanner.jsp</value>
```suggestion
      <value>/WEB-INF/jsp/portlet/banner.jsp</value>
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/portlet.xml
> +      <keywords>Images</keywords>
```suggestion
      <title>Banner</title>
      <keywords>Banner</keywords>
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/portlet/portletBanner.jsp
> +      require(['PORTLET/social-portlet/ImagesPortlet'], app => app.init(
```suggestion
      require(['PORTLET/social-portlet/BannerPortlet'], app => app.init(
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/gatein-resources.xml
> +    <name>ImagesPortlet</name>
```suggestion
    <name>BannerPortlet</name>
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/Portlets_en.properties
> +#                              Portlet Banner                                   #
```suggestion
#                              Banner                                   #
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/Portlets_en.properties
> +portletBanner.title.ChangeBanner=Change background
```suggestion
portletBanner.title.BannerUpdated=Background successfully updated
banner.title.BannerDeleted=Background successfully deleted
banner.title.deleteBanner=Delete Background
banner.title.ChangeBanner=Change background
```

Translations to be verified with O

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/java/org/exoplatform/social/portlet/ImagesPortlet.java
> +public class ImagesPortlet extends GenericPortlet {
```suggestion
public class BannerPortlet extends GenericPortlet {
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/java/org/exoplatform/social/portlet/ImagesPortlet.java
> +
Remove empty line

2023-08-17 15:54 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/social/service-configuration.xml
> +    <type>org.exoplatform.social.rest.impl.portletBanner.PortletBannerRestService</type>
```suggestion
    <type>org.exoplatform.social.rest.impl.banner.BannerRest</type>
```

2023-08-17 15:54 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/social/core-configuration.xml
> +        <type>org.exoplatform.social.core.portletBanner.PortletBannerServiceImpl</type>
```suggestion
        <key>org.exoplatform.social.core.banner.BannerService</key>
        <type>org.exoplatform.social.core.banner.BannerServiceImpl</type>
```

2023-08-17 15:54 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/portlet-banner/portletBannerService.js
> +export function getPortletBanner(uploadFileId) {
```suggestion
export function getBanner(uploadFileId) {
```

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +@Tag(name = VersionResources.VERSION_ONE + "/social/portletBanner", description = "Managing portlet Banner")
```suggestion
@Path(VersionResources.VERSION_ONE + "/social/banner")
@Tag(name = VersionResources.VERSION_ONE + "/social/banner", description = "Managing banner")
```
We should check if /social is adequate with the URL

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +public class PortletBannerRestService implements ResourceContainer {
```suggestion
public class BannerRest implements ResourceContainer {
```

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +  private static final Log           LOG = ExoLogger.getLogger(PortletBannerRestService.class);
```suggestion
  private static final Log           LOG = ExoLogger.getLogger(BannerRest.class);
```

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +  private  PortletBannerService portletBannerService;
```suggestion
  private BannerService bannerService;
```

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +  public Response updatePortletBanner(@Parameter(description = "upload file id")
this is the getBanner method ?

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +  public Response getPortletBannerStream(@Context
where this method is used ?

2023-08-17 15:54 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/entity/PortletBannerEntity.java
> +public class PortletBannerEntity {
```suggestion
public class BannerEntity {
```

2023-08-17 15:54 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +  public static String getBaseURLSocialPortletBannerRest() {
```suggestion
  public static String getBaseURLBannerRest() {
```

2023-08-17 15:54 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +      baseURLSocialPortletBannerRest = getBaseURLSocialRest() + "/portletBanner";
```suggestion
      baseURLSocialPortletBannerRest = getBaseURLSocialRest() + "/banner";
```

2023-08-17 15:54 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +      return new StringBuilder(getBaseURLSocialPortletBannerRest()).append("/")
do you need all this params ?

2023-08-18 16:07 UTC, azayati requested changes
see review

2023-08-18 16:07 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +  public Response getPortletBannerStream(@Context
```suggestion
  public Response getBannerStream(@Context
```

2023-08-18 16:07 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +      LOG.error("Error when retrieving portlet banner", e);
```suggestion
      LOG.error("Error when retrieving banner", e);
```

2023-08-18 16:07 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/portletBanner/PortletBannerRestService.java
> +      LOG.error("Error when retrieving portlet banner stream", e);
```suggestion
      LOG.error("Error when retrieving banner stream", e);
```

2023-08-18 16:07 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/portletBanner/PortletBannerServiceImpl.java
> +
remove empty line

2023-08-18 16:07 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/portletBanner/PortletBannerServiceImpl.java
> +  public Long updatePortletBanner(String remoteId, String uploadFileId) {
```suggestion
  public Long getBanner(String remoteId, String uploadFileId) {
```

2023-08-18 16:07 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/portletBanner/PortletBannerServiceImpl.java
> +  public InputStream getPortletBannerStream(String fileId) {
```suggestion
  public InputStream getBannerStream(String fileId) {
```

2023-08-18 16:07 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/portletBanner/PortletBannerServiceImpl.java
> +  public InputStream getPortletImageAsStream(String fileId) {
you can add this code directly in the above method

2023-08-21 14:42 UTC, azayati requested changes

2023-08-21 14:42 UTC, azayati commented on component/api/src/main/java/org/exoplatform/social/core/banner/BannerService.java
> + * Copyright (C) 2023 eXo Platform SAS.
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/banner/BannerServiceImpl.java
> + * Copyright (C) 2023 eXo Platform SAS.
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/entity/BannerEntity.java
> + * Copyright (C) 2023 eXo Platform SAS.
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/banner/BannerRestService.java
> + * This program is free software: you can redistribute it and/or modify
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/java/org/exoplatform/social/portlet/BannerPortlet.java
> +package org.exoplatform.social.portlet;
add meeds header

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/banner/bannerService.js
> +export function getBanner(uploadFileId) {
add meeds header

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/banner/components/Banner.vue
> +<template>
add meeds header

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/banner/initComponents.js
> + * Copyright (C) 2023 eXo Platform SAS.
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/banner/main.js
> +/*
file header should be meeds one not eXo one

2023-08-21 14:42 UTC, azayati commented on webapp/portlet/src/main/java/org/exoplatform/social/portlet/BannerPortlet.java
> +import javax.portlet.*;
import the exact packages

2023-08-21 14:42 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/banner/BannerRestService.java
> +import javax.ws.rs.*;
import the exact packages

2023-09-11 10:11 UTC, closed without merging