fix: Can't make search by email in usersmanagement - EXO-65032 - Meeds-io/meeds#1085
Meeds-io/social pull request #2788
Opened 2023-09-04 10:16 UTC by akhanfir

Prior to this change, when open usersManagement interface and search for users by their mail or login, search shows no results.To fix this problem, added the search by email or login in the search query.After this change, In user management search, should retrieve users by first&last names, emails & usernames.

2023-09-04 10:39 UTC, ahamdi commented
@akhanfir Could you resolve conflicts ?

2023-09-06 12:18 UTC, rdenarie requested changes
Can you fix the sonar bug ?
In addition can you try to add a unit test to cover the added lines ?

Thanks

2023-09-25 16:02 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-10-02 13:24 UTC, ahamdi commented on component/service/src/main/java/org/exoplatform/social/rest/impl/user/UserRestResourcesV1.java
> +      filter.setSearchEmail(searchEmail ? true : false);
```suggestion
      filter.setSearchEmail(searchEmail);
```

2023-10-03 08:36 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-10-17 08:32 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2024-01-12 09:28 UTC, mkrout submitted a review, later dismissed

2024-01-30 09:31 UTC, Jihed525 commented
@rdenarie can you have a look ?
FOr test coverage, @akhanfir confirms that it will be handled in the next pr https://github.com/Meeds-io/social/pull/2776

2024-01-30 10:42 UTC, rdenarie approved these changes
ok for me

2024-01-30 10:42 UTC, merged