feat: implement site banner - EXO-65534 - Meeds-io/MIPs#72
Meeds-io/social pull request #2851
Opened 2023-09-14 11:35 UTC by GouadriaHanen

2023-09-14 14:56 UTC, azayati requested changes

2023-09-14 14:56 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/RestUtils.java
> +  public static String buildAttachmentUrl(String siteName, String type) {
why not adding that here https://github.com/Meeds-io/social/blob/84be6394c4a559220ef01c6b26e421b73ff0acac/component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java#L47 ?

2023-09-14 14:56 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +                                                           "/images/sites/" + siteName.toLowerCase() + ".png"));
```suggestion
                                                           "/images/sites/banner/" + siteName.toLowerCase() + "Banner.png"));
```

2023-09-14 14:56 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +    InputStream is =  portalContainer.getPortalContext()
```suggestion
    InputStream is = portalContainer.getPortalContext()
```

2023-09-14 14:56 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +  private InputStream getDefaultBannerInputStream(String siteName) throws IOException {
```suggestion
  private InputStream getDefaultSiteBannerInputStream(String siteName) throws IOException {
```

2023-09-14 14:56 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +    return new ByteArrayInputStream(defaultSiteBanner);
why not returning directly is ?

2023-09-14 14:56 UTC, azayati commented on component/service/src/test/java/org/exoplatform/social/rest/impl/site/SiteRestTest.java
> +import org.exoplatform.social.rest.api.RestUtils;
remove useless imports

2023-09-14 14:56 UTC, azayati commented on component/service/src/test/java/org/exoplatform/social/rest/impl/site/SiteRestTest.java
> +  private ContainerEntity createContainerInstance() {
why do we need ContainerEntity ?

2023-09-22 13:53 UTC, azayati requested changes

2023-09-22 13:53 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +  public static String buildAttachmentUrl(String siteName, String type, boolean isDefault) {
```suggestion
  public static String buildSiteBannertUrl(PortalConfig site) {
```
try to call the private existing method buildAttachmentUrl with the needed site params

2023-09-22 13:53 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +  public static String generateAttachmentToken(String siteName, String attachmentType) {
IMO we can use the already existing method generateAttachmentToken

2023-09-22 13:53 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +  public static boolean isAttachmentTokenValid(String token, String siteName, String attachmentType) {
IMO we can use the already existing method isAttachmentTokenValid

2023-09-22 13:53 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +  private InputStream getDefaultBannerInputStream(String siteName) throws IOException {
can you consider this https://github.com/Meeds-io/social/pull/2851/files#r1326055319 ?

2023-09-22 13:53 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +    return new ByteArrayInputStream(defaultSiteBanner);
can you consider this https://github.com/Meeds-io/social/pull/2851/files#r1326065689 ?

2023-09-22 13:53 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +      @ApiResponse(responseCode = "400", description = "Invalid query input"),
I think we don't have the 400 error

2023-09-22 13:53 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/service/LinkProvider.java
> +  public static final String     ATTACHMENT_BANNER_TYPE   = "banner";
```suggestion
  public static final String     SITE_BANNER_TYPE   = "banner";
```

2023-09-22 13:53 UTC, azayati commented on component/service/src/test/java/org/exoplatform/social/rest/impl/site/SiteRestTest.java
> +  private ContainerEntity createContainerInstance() {
can you consider this https://github.com/Meeds-io/social/pull/2851/files#r1326083267 ?

2023-09-22 15:45 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-09-25 10:29 UTC, azayati approved these changes
LGTM

2023-09-25 10:30 UTC, merged