feat: fix left navigation UI issues and filter navigations to display - EXO-66384 - Meeds-io/MIPs#72
Meeds-io/social pull request #2946
Opened 2023-09-26 13:19 UTC by GouadriaHanen

2023-09-28 11:37 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-10-02 13:50 UTC, azayati requested changes

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/EntityBuilder.java
> +    boolean hasPageChild = false;
```suggestion
    boolean hasPageChildNode = false;
```

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/EntityBuilder.java
> +  private static List<UserNodeRestEntity> removeEmptyNavigations(List<UserNodeRestEntity> userNodeList) {
```suggestion
  private static void removeGroupNodesWithoutPageChildNodes(List<UserNodeRestEntity> userNodeList) {
```
Add a comment to explain what this method does exactly.

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/EntityBuilder.java
> +                                           boolean excludeEmptyNavigation,
```suggestion
                                           boolean excludeGroupNodesWithoutPageChildNodes,
```

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/EntityBuilder.java
> +  private static boolean hasUserNodePageChild(UserNodeRestEntity userNode) {
```suggestion
  private static boolean hasPageChildNode(UserNodeRestEntity userNode) {
```

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +                           boolean excludeEmptyNavigations,
```suggestion
                           @Parameter(description = "to exclude group nodes without page child nodes")
                           @DefaultValue("false")
                           @QueryParam("excludeGroupNodesWithoutPageChildNodes")
                           boolean excludeGroupNodesWithoutPageChildNodes,
```

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +                           @Parameter(description = "to check , in expandNavigations case , the navigation nodes scheduling start and end dates")
```suggestion
                           @Parameter(description = "to check, in expandNavigations case, the navigation nodes scheduling start and end dates")
```

2023-10-02 13:50 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/site/SiteRest.java
> +                              @Parameter(description = "to check , in expandNavigations case , the navigation nodes scheduling start and end dates")
see above

2023-10-02 13:50 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/common/js/SiteService.js
> +  formData.append('excludeEmptyNavigations', excludeEmptyNavigations);
see above

2023-10-03 12:53 UTC, merged