Merge Review composer UX - Meeds-io/MIPs#54
Meeds-io/social pull request #2955
Opened 2023-09-28 12:03 UTC by MayTekayaa

This change will merge the review composer UX MIP.

2023-10-02 08:25 UTC, rdenarie commented on webapp/portlet/src/main/webapp/vue-apps/activity-stream/components/toolbar/ActivityStreamFilterDrawer.vue
> +  Copyright (C) 2022 Meeds Association
```suggestion
  Copyright (C) 2023 Meeds Association
```

2023-10-02 16:34 UTC, MayTekayaa commented on webapp/portlet/src/main/webapp/vue-apps/activity-stream/components/toolbar/ActivityStreamFilterDrawer.vue
> +  Copyright (C) 2022 Meeds Association
done!

2023-10-03 08:30 UTC, rdenarie requested changes

2023-10-03 08:30 UTC, rdenarie commented on webapp/portlet/src/main/webapp/groovy/social/webui/UISocialPortalApplicationHead.gtmpl
> +     eXo.env.portal.postToNetworkEnabled = <%=PropertyManager.getProperty("exo.feature.PostToNetwork.enabled")%>;
@boubaker should we use featureService instead of propertyManager ?
```suggestion
     eXo.env.portal.postToNetworkEnabled =  <%=featureService.isFeatureActiveForUser("PostToNetwork", userName)%>;
```

2023-10-03 08:36 UTC, boubaker commented on webapp/portlet/src/main/webapp/groovy/social/webui/UISocialPortalApplicationHead.gtmpl
> +     eXo.env.portal.postToNetworkEnabled = <%=PropertyManager.getProperty("exo.feature.PostToNetwork.enabled")%>;
Yes, good idea, if we need to enable the feature for some users only.

2023-10-03 10:19 UTC, rdenarie submitted a review, later dismissed

2023-10-03 10:28 UTC, rdenarie approved these changes

2023-10-03 10:40 UTC, merged