feat: Configure Platform Settings site with its navigations - EXO-66546 - Meeds-io/MIPs#88
Meeds-io/social pull request #3031
Opened 2023-10-10 11:56 UTC by IlhemEssaadi

2023-10-11 13:12 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-10-11 22:52 UTC, azayati requested changes

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/resources/locale/navigation/portal/administration_en.properties
> +# Copyright (C) 2020 eXo Platform SAS.
update header

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/navigation.xml
> +  <page-nodes>
Remove <visibility>DISPLAYED</visibility> , it is the default value

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/navigation.xml
> +          <page-reference>portal::/platform/users::spacesAdministration</page-reference>
```suggestion
          <page-reference>portal::administration::spacesAdministration</page-reference>
```

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/pages.xml
> +<?xml version="1.0" encoding="UTF-8"?>
update header

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/portal.xml
> +  Copyright (C) 2022 Meeds Association contact@meeds.io
update header

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/portal.xml
> +  <displayed>false</displayed>
put this tag <displayed> after <label> tag

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/social-portal-configuration.xml
> +         <value> ${exo.social.portalConfig.administration.metadata.override:true} </value>
```suggestion
         <value>true</value>
```

2023-10-11 22:52 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/social-portal-configuration.xml
> +          <description>description</description>
```suggestion
```

2023-10-11 22:53 UTC, azayati requested changes

2023-10-11 22:53 UTC, azayati commented on extension/war/src/main/resources/locale/navigation/portal/administration_en.properties
> +# Copyright (C) 2020 eXo Platform SAS.
you should declare the file into https://github.com/Meeds-io/social/blob/develop/translations.properties#L64 like done for global site, in order to be considered by crowdin

2023-10-11 23:08 UTC, azayati requested changes

2023-10-11 23:08 UTC, azayati commented on extension/war/src/main/webapp/WEB-INF/conf/social-extension/portal/portal/administration/portal.xml
> +<portal-config>
```suggestion
<portal-config
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.gatein.org/xml/ns/gatein_objects_1_10 http://www.gatein.org/xml/ns/gatein_objects_1_10"
        xmlns="http://www.gatein.org/xml/ns/gatein_objects_1_10">
```

2023-10-12 10:05 UTC, azayati approved these changes
LGTM

2023-10-12 10:05 UTC, merged