Add the space administration portlet to the ManageSpaceGRP load group - EXO-68206 - Meeds-io/meeds#1467
Meeds-io/social pull request #3346
Opened 2023-12-22 08:08 UTC by IlhemEssaadi

2023-12-22 16:10 UTC, azayati requested changes

2023-12-22 16:10 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +      type="drawers-manage-space-actions" />
```suggestion
      name="manageSpaceDrawer"
      type="manage-space-drawers" />
```

2023-12-22 16:10 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +            type="button-manage-space-actions"
```suggestion
            name="manageSpaceActions"
            type="manage-space-actions"
```

2023-12-22 18:40 UTC, azayati requested changes

2023-12-22 18:40 UTC, azayati commented on webapp/portlet/src/main/webapp/vue-apps/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +      name="manageSpaceDrawer"
```suggestion
      name="manageSpaceDrawers"
```

2023-12-22 21:51 UTC, azayati submitted a review, later dismissed
LGTM

2023-12-26 12:11 UTC, ahamdi approved these changes

2023-12-26 13:25 UTC, merged