Task-35725 : Hide change password from settings for LDAP users.
Meeds-io/social pull request #384
Opened 2020-10-29 20:30 UTC by ahmadmido

. This PR will assure those only internal exo users can show settings to change password.
. LDAP users can't edit their password.

2020-11-04 17:00 UTC, azayati requested changes
See review

2020-11-04 17:00 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/components/UserSettingSecurity.vue
> +      if(data && data.isInternal){
this.canChangePassword= data && (data.isInternal || exo.portal.allow.change.external.password == true) ;

2020-11-04 17:00 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/components/UserSettingSecurity.vue
> +    isInternal: false,
```suggestion
    canChangePassword: true,
```

2020-11-04 17:00 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/components/UserSettingSecurity.vue
> +  <v-app v-if="displayed && isInternal">
```suggestion
  <v-app v-if="displayed && canChangePassword">
```

2020-11-04 17:00 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/EntityBuilder.java
> +      userEntity.setIsInternal(isInternal(profile.getIdentity().getRemoteId()));
```suggestion
      userEntity.setIsInternal(isInternal(userEntity.getUsername());
```

2020-11-04 17:00 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/entity/ProfileEntity.java
> +  public static final String ISINTERNAL          = "isInternal";
```suggestion
  public static final String IS_INTERNAL          = "isInternal";
```

2020-11-04 17:00 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/entity/ProfileEntity.java
> +    DataEntity dataEntity = getDataEntity();
```suggestion
    setProperty("IS_INTERNAL", IsInternal);
```

2020-11-05 09:51 UTC, azayati requested changes
See review

2020-11-05 09:51 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/components/UserSettingSecurity.vue
> +      if(data && data.IS_INTERNAL){
```suggestion
     this.canChangePassword= data && (data.isInternal || exo.portal.allow.change.external.password == true) ;
```
try this instead

2020-11-05 09:51 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/main.js
>      document.dispatchEvent(new CustomEvent('hideTopBarLoading'));
why this is modified ?

2020-11-05 09:51 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/main.js
> +        template: `<user-setting-security id="${appId}" v-cacheable :allowChangeExternalPassword="allowChangeExternalPassword" />`,
```suggestion
        template: `<user-setting-security id="${appId}" allowChangeExternalPassword="${allowChangeExternalPassword}" v-cacheable />`,
```

2020-11-05 09:51 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/main.js
> +        data: () => ({
not needed

2020-11-05 09:51 UTC, azayati commented on webapp/portlet/src/main/webapp/user-setting-security/components/UserSettingSecurity.vue
> +    skeleton: true,
why skeleton added ?

2020-11-05 10:44 UTC, ahmadmido commented on webapp/portlet/src/main/webapp/user-setting-security/main.js
> +        template: `<user-setting-security id="${appId}" v-cacheable :allowChangeExternalPassword="allowChangeExternalPassword" />`,
Done !

2020-11-05 12:27 UTC, azayati commented
I have suggested another solution to @ahmadmido, to get the user from conversation state from the jsp file, check the condition of canChangePassword which will be (!ssoEnabled && (internalUser || exo.portal.allow.change.external.password == true), that way we can decide if we keep the profileentity modification or not.
@ahamdi can you give your feedback on that ?

2020-11-06 09:01 UTC, azayati approved these changes
LGTM

2020-11-06 14:02 UTC, azayati requested changes
See review

2020-11-06 14:02 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/userSettingSecurity.jsp
> +  String allowChangeExternalPassword = System.getProperty("exo.portal.allow.change.external.password");
```suggestion
  boolean allowChangeExternalPassword = System.getProperty("exo.portal.allow.change.external.password", "false").equals("true");
```

2020-11-06 14:02 UTC, azayati commented on webapp/portlet/src/main/webapp/WEB-INF/jsp/userSettingSecurity.jsp
> +<% if (!ssoEnabled && (isInternalUser || allowChangeExternalPassword.equals("true"))) { %>
```suggestion
<% if (!ssoEnabled && (isInternalUser || allowChangeExternalPassword )) { %>
```

2020-11-06 16:09 UTC, azayati commented
To be tested @ahmadmido

2020-11-06 16:09 UTC, azayati submitted a review, later dismissed
LGTM

2020-11-06 21:16 UTC, azayati approved these changes
LGTM after QA validation

2020-11-09 12:28 UTC, merged