TASK-35540: Inviting a guest to a space
Meeds-io/social pull request #414
Opened 2020-11-17 10:47 UTC by AzmiTouil

2020-11-17 10:52 UTC, boubaker submitted a review, later dismissed
I didn't get the difference between regular user and external user. Can you explain more please

2020-11-17 13:28 UTC, plamarque commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +          <v-btn icon @click="removeEternal(user)">
typo
```suggestion
          <v-btn icon @click="removeExternal(user)">
```

2020-11-17 13:28 UTC, plamarque commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +    checkEternal(event) {
```suggestion
    checkExternal(event) {
```

2020-11-17 13:29 UTC, plamarque commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +    removeEternal(user) {
```suggestion
    removeExternal(user) {
```

2020-11-17 13:29 UTC, plamarque commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +            <v-icon color="#BE4141">
can we avoid using hard coded color and use a css variable instead ?

CC @azayati

2020-11-26 08:11 UTC, azayati requested changes
See review

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +        spaceService.AddExternalSpaceInvitation(space.getId(), email);
spaceService.addExternalSpaceInvitation

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +    SpaceExternalInvitationEntity externalInvitation = new SpaceExternalInvitationEntity();
```suggestion
    SpaceExternalInvitationEntity spaceExternalInvitation = new SpaceExternalInvitationEntity();
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public List<String> getSpaceIdsByExternalEmail(String email) {
```suggestion
  public List<String> findExternalInvitationsSpacesByEmail(String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public void deleteExternalUserInvitations(String email) {
```suggestion
  public void deleteSpaceExternalInvitations(String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +    return spaceExternalInvitationDAO.getSpaceIdsByExternalEmail(email);
```suggestion
    return spaceExternalInvitationDAO.findExternalInvitationsSpacesByEmail(email);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/SpaceExternalInvitationDAO.java
> +     * get the list of spaces ids by external email
```suggestion
     * find the list of external invitations spaces by email
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/SpaceExternalInvitationDAO.java
> +     * get the list of external invitations by space Id
```suggestion
     * find the list of space external invitations by space Id
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +    return spaceExternalInvitationDAO.getExternalSpaceInvitations(spaceId);
```suggestion
    return spaceExternalInvitationDAO.findSpaceExternalInvitationsBySpaceId(spaceId);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +    spaceExternalInvitationDAO.deleteExternalUserInvitations(email);
```suggestion
    spaceExternalInvitationDAO.deleteSpaceExternalInvitations(email);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +        query.setParameter("userEmail", email);
```suggestion
        query.setParameter("email", email);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +                .setParameter("userEmail", email)
```suggestion
                .setParameter("email", email)
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +    public SpaceExternalInvitationEntity create(SpaceExternalInvitationEntity entity) {
Method not needed IMO since you already inherit it from super dao

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/listeners/SocialMembershipListenerImpl.java
> +      SpaceService spaceService = container.getComponentInstanceOfType(SpaceService.class);
```suggestion
      SpaceService spaceService = CommonsUtils.getService(SpaceService.class);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/listeners/SocialMembershipListenerImpl.java
> +      ExoContainer container = ExoContainerContext.getCurrentContainer();
Not needed

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/listeners/SocialMembershipListenerImpl.java
> +        Space space = spaceService.getSpaceById(spaceId);
not needed

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/space/impl/SpaceServiceImpl.java
> +  public List<SpaceExternalInvitationEntity> getExternalSpaceInvitations(String spaceId) {
```suggestion
  public List<SpaceExternalInvitationEntity> getSpaceExternalInvitationsBySpaceId(String spaceId) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/space/impl/SpaceServiceImpl.java
> +  public List<String> getSpaceIdsByExternalEmail(String email) {
```suggestion
  public List<String> getExternalInvitationsSpacesByEmail(String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/space/impl/SpaceServiceImpl.java
> +  public void deleteExternalUserInvitations(String email) {
```suggestion
  public void deleteSpaceExternalInvitations(String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/space/spi/SpaceService.java
> +   * @return a list of external invitations in space
See above SpaceServiceImpl

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/storage/api/SpaceStorage.java
> +  public List<SpaceExternalInvitationEntity> getExternalSpaceInvitations(String spaceId) throws SpaceStorageException;
Use same methods names as with SpaceServiceImpl

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/storage/cache/CachedSpaceStorage.java
> +  @Override
Use same methods names as with SpaceStorage

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public void addExternalSpaceInvitation(String spaceId, String email) {
```suggestion
  public void saveSpaceExternalInvitation(String spaceId, String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public List<SpaceExternalInvitationEntity> getExternalSpaceInvitations(String spaceId) {
```suggestion
  public List<SpaceExternalInvitationEntity> findSpaceExternalInvitationsBySpaceId(String spaceId) {
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/SpaceExternalInvitationDAO.java
> +public interface SpaceExternalInvitationDAO extends GenericDAO<SpaceExternalInvitationEntity, Long> {
Change methods names according to RDBMSSpaceStorageImpl.java remarks above

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/SpaceExternalInvitationDAO.java
> +     * delete external invitations
```suggestion
     * delete space external invitations by email
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +public class SpaceExternalInvitationDAOImpl extends GenericDAOJPAImpl<SpaceExternalInvitationEntity, Long> implements SpaceExternalInvitationDAO {
Change methods names according to RDBMSSpaceStorageImpl.java remarks above

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +        TypedQuery<SpaceExternalInvitationEntity> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.getExternalSpaceInvitations", SpaceExternalInvitationEntity.class);
```suggestion
        TypedQuery<SpaceExternalInvitationEntity> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.getSpaceExternalInvitations", SpaceExternalInvitationEntity.class);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +        TypedQuery<String> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.getSpaceIdsByExternalEmail", String.class);
```suggestion
        TypedQuery<String> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.findExternalInvitationsSpacesByEmail", String.class);
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +        getEntityManager().createNamedQuery("SocSpaceExternalInvitations.deleteExternalUserInvitations")
```suggestion
        getEntityManager().createNamedQuery("SocSpaceExternalInvitations.deleteSpaceExternalInvitations")
```

2020-11-26 08:11 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/space/impl/SpaceServiceImpl.java
> +  public void addExternalSpaceInvitation(String spaceId, String email) {
```suggestion
  public void saveSpaceExternalInvitation(String spaceId, String email) {
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/entity/SpaceEntity.java
> +  public SpaceEntity setExternalInvitedUsers(List<String> invitedExternalUser) {
```suggestion
  public SpaceEntity setExternalInvitedUsers(List<String> externalInvitedUsers) {
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +      for (String email : model.getExternalInvitedUsers()) {
```suggestion
      for (String externalInvitedUser : model.getExternalInvitedUsers()) {
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +        spaceService.addExternalSpaceInvitation(space.getId(), email);
You should check into addExternalSpaceInvitation methodif the entry is not already present in the table

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +   * Checks if is space member.
```suggestion
   * Checks if is the given userId is a space member.
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +  @ApiOperation(value = "check if user is a member of a specific space or not",
```suggestion
  @ApiOperation(value = "Checks if the given user is a member of a specific space or not",
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +    if (space == null || (!spaceService.isMember(space, authenticatedUser) && !spaceService.isSuperManager(authenticatedUser))) {
```suggestion
    if (space == null ||  (! spaceService.isManager(space, authenticatedUser) && ! spaceService.isSuperManager(authenticatedUser))) {
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +    if (space == null) {
```suggestion
  String authenticatedUser = ConversationState.getCurrent().getIdentity().getUserId();
   if (space == null || (!spaceService.isMember(space, authenticatedUser) && !spaceService.isSuperManager(authenticatedUser)))
```

2020-11-26 08:11 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +    List<SpaceExternalInvitationEntity> externalSpaceInvitations = spaceService.getExternalSpaceInvitations(id);
```suggestion
    List<SpaceExternalInvitationEntity> spaceExternalInvitations = spaceService.getExternalSpaceInvitations(id);
```

2020-11-26 08:11 UTC, azayati commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +        externalInvitedUsers:this.externalInvitedUsers
```suggestion
        externalInvitedUsers: this.externalInvitedUsers
```

2020-11-26 08:11 UTC, azayati commented on webapp/portlet/src/main/webapp/space-members/components/SpaceInvitationDrawer.vue
> +                    this.alreadyExistAlert = `<span style="font-style: italic;">${email}</span> ${this.$t('peopleList.label.alreadyMember')}`;
put this html code into template tag, then for setTimeout use show/hide

2020-11-26 10:38 UTC, azayati requested changes
LGTM

2020-11-26 10:38 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/user/UserRestResourcesV1.java
> +    jsonObject.put("id", identity.getProfile().getIdentity().toString());
```suggestion
    jsonObject.put("id", identity.toString());
```

2020-11-26 13:15 UTC, azayati requested changes
See review

2020-11-26 13:15 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/space/SpaceRestResourcesV1.java
> +    if (space == null || (!spaceService.isManager(space, authenticatedUser) && !spaceService.isSuperManager(authenticatedUser))) {
```suggestion
if (space == null || (!spaceService.isMember(space, authenticatedUser) && !spaceService.isSuperManager(authenticatedUser)))
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public List<SpaceExternalInvitationEntity> getSpaceExternalInvitations(String spaceId) {
```suggestion
  public List<SpaceExternalInvitationEntity> findSpaceExternalInvitationsBySpaceId(String spaceId) {
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +    return spaceExternalInvitationDAO.getSpaceExternalInvitations(spaceId);
```suggestion
    return spaceExternalInvitationDAO.findSpaceExternalInvitationsBySpaceId(spaceId);
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/SpaceExternalInvitationDAOImpl.java
> +        TypedQuery<SpaceExternalInvitationEntity> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.getSpaceExternalInvitations", SpaceExternalInvitationEntity.class);
```suggestion
        TypedQuery<SpaceExternalInvitationEntity> query = getEntityManager().createNamedQuery("SocSpaceExternalInvitations.findSpaceExternalInvitationsBySpaceId", SpaceExternalInvitationEntity.class);
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/entity/SpaceExternalInvitationEntity.java
> +        @NamedQuery(name = "SocSpaceExternalInvitations.getSpaceExternalInvitations", query = "SELECT invit FROM SocSpaceExternalInvitations invit WHERE invit.spaceId = :spaceId"),
```suggestion
        @NamedQuery(name = "SocSpaceExternalInvitations.findSpaceExternalInvitationsBySpaceId", query = "SELECT invit FROM SocSpaceExternalInvitations invit WHERE invit.spaceId = :spaceId"),
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/test/java/org/exoplatform/social/core/jpa/storage/dao/SpaceExternalInvitationDAOTest.java
> +    public void testGetSpaceExternalInvitations() {
```suggestion
    public void testFindSpaceExternalInvitationsBySpaceId() {
```

2020-11-26 13:15 UTC, azayati commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSSpaceStorageImpl.java
> +  public void deleteUserExternalInvitations(String email) {
```suggestion
  public void deleteExternalUserInvitations(String email) {
```

2020-11-26 13:58 UTC, azayati approved these changes
LGTM

2020-11-26 14:24 UTC, azayati approved these changes
LGTM

2020-11-26 15:00 UTC, merged