Task-36728 : Delete externals users Visibility from people directory and contact suggestions.
Meeds-io/social pull request #449
Opened 2020-12-04 12:25 UTC by ahmadmido

2020-12-07 08:55 UTC, azayati requested changes
See review

2020-12-07 08:55 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/RestUtils.java
> +    return getIdentity(userId).isMemberOf(EXTERNAL_GROUP);
```suggestion
OrganizationService organizationService = CommonsUtils.getService(OrganizationService.class);
    return organizationService.getMembershipHandler().findMembershipsByUserAndGroup(userId, EXTERNAL_GROUP).size() > 0;
```

2020-12-07 08:55 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/api/RestUtils.java
> +  private static org.exoplatform.services.security.Identity getIdentity(String userId) throws Exception {
Not needed

2020-12-09 19:09 UTC, azayati requested changes
We need to change the query by adding like below:

SELECT distinct identity.* FROM plf6.soc_identities as identity inner join plf6.soc_identity_properties as properties on identity.identity_id = properties.identity_id and not exists (select properties_tmp.IDENTITY_ID from plf6.soc_identity_properties as properties_tmp where  properties_tmp.IDENTITY_ID = identity.IDENTITY_ID and  properties_tmp.name = "external" and  properties_tmp.value="true");

2020-12-09 19:10 UTC, azayati requested changes
See review

2020-12-09 19:10 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/impl/user/UserRestResourcesV1.java
> +      if(RestUtils.isMemberOfExternalGroup(identity.getRemoteId())) continue;
No needed after changing the query

2020-12-09 19:10 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/rest/suggest/PeopleRestServices.java
> +        if(RestUtils.isMemberOfExternalGroup(id.getRemoteId())) continue;
you should check directly id.getProfile.getProperty("external")

2020-12-15 14:13 UTC, ahamdi requested changes

2020-12-15 14:13 UTC, ahamdi commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSIdentityStorageImpl.java
> +      for(IdentityEntity identityEntity : list.load(-1, -1)){
This is a performance killer, please rework it and avoid FOR loops.

2020-12-24 09:21 UTC, closed without merging