Task-37293: Ability to enable/disable the external invitation feature
Meeds-io/social pull request #450
Opened 2020-12-07 16:35 UTC by AzmiTouil

2020-12-07 17:09 UTC, azayati requested changes
See review

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/social/SpacesAdministrationPortlet_en.properties
> +social.spaces.administration.manageSpaces.inviteNewExternal=Invite new external
Add FR labels also

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +      ExternalFeatureEnabled: true
```suggestion
      externalFeatureEnabled: true
```

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/spacesAdministrationServices.js
> +      throw new Error('Error External Feature settings');
```suggestion
      throw new Error('Error when getting External Feature settings');
```

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/spacesAdministrationServices.js
> +  }).then(resp => {
To be verified

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/spacesAdministrationServices.js
> +  }).then(resp => {
To be verified

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/spacesAdministrationServices.js
> +      throw new Error('Error setting External Feature settings');
```suggestion
      throw new Error('Error when setting External Feature settings');
```

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +                @change="saveExternalFeatureStatus(!ExternalFeatureEnabled)"/>
```suggestion
                @change="saveExternalFeatureStatus(!externalFeatureEnabled)"/>
```

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +      this.ExternalFeatureEnabled = status !== null ? status.value === 'true' : true;
```suggestion
      this.externalFeatureEnabled= status !== null ? status.value === 'true' : true;
```

2020-12-07 17:09 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/spacesAdministrationServices.js
> +      value: !status,
```suggestion
      value: status,
```

2020-12-08 11:08 UTC, azayati requested changes
See review

2020-12-08 11:08 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +    this.initSpaces();
Revert this file

2020-12-08 11:08 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationSpacesPermissions.vue
> +<style>
Remove this useless block

2020-12-08 11:23 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationManageSpaces.vue
> +    this.initSpaces();
Done!

2020-12-08 11:23 UTC, AzmiTouil commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationSpacesPermissions.vue
> +<style>
Done!

2020-12-08 13:10 UTC, azayati approved these changes
LGTM after QA validation

2020-12-08 15:21 UTC, azayati requested changes
See review

2020-12-08 15:21 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/social/SpacesAdministrationPortlet_fr.properties
> +social.spaces.administration.permissions.toDisableExternal=Pour d\u00E9sactiver la capacit\u00E9 d'inviter de nouveaux membres externes.
```suggestion
social.spaces.administration.permissions.enableDisableExternal=Pour activer/d\u00E9sactiver la capacit\u00E9 d'inviter de nouveaux membres externes.
```

2020-12-08 15:21 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/social/SpacesAdministrationPortlet_en.properties
> +social.spaces.administration.permissions.toDisableExternal=To disable the capacity to invite any new external members.
```suggestion
social.spaces.administration.permissions.enableDisableExternal=To enable/disable the capacity to invite any new external members.
```

2020-12-08 15:21 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationSpacesPermissions.vue
> +              {{ $t('social.spaces.administration.permissions.toDisableExternal') }}
```suggestion
              {{ $t('social.spaces.administration.permissions.enableDisableExternal') }}
```

2020-12-08 18:03 UTC, azayati requested changes
See review

2020-12-08 18:03 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationSpacesPermissions.vue
> +      this.statusLoaded = true;
externalFeatureStatusLoaded

2020-12-08 18:03 UTC, azayati commented on webapp/portlet/src/main/webapp/spaces-administration/components/ExoSpacesAdministrationSpacesPermissions.vue
>      spacesAdministrationServices.isExternalFeatureActive().then(status => {
Put this into a method getExternalFeatureStatus

2020-12-09 08:18 UTC, azayati requested changes
See review

2020-12-09 08:18 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/social/SpacesAdministrationPortlet_en.properties
> +social.spaces.administration.permissions.enableDisableExternal=To enable/disable the capacity to invite any new external members.
```suggestion
social.spaces.administration.permissions.enableDisableExternal=To enable or disable the capacity to invite any new external members.
```

2020-12-09 08:18 UTC, azayati commented on webapp/portlet/src/main/resources/locale/portlet/social/SpacesAdministrationPortlet_fr.properties
> +social.spaces.administration.permissions.enableDisableExternal=Pour activer/d\u00E9sactiver la capacit\u00E9 d'inviter de nouveaux membres externes.
```suggestion
social.spaces.administration.permissions.enableDisableExternal=Pour activer ou d\u00E9sactiver la capacit\u00E9 d'inviter de nouveaux membres externes.
```

2020-12-09 09:08 UTC, azayati approved these changes
LGTM after QA validation

2020-12-09 09:32 UTC, merged