TASK-38016: Enhance suggester service to allow restrict assigning to project participants
Meeds-io/social pull request #467
Opened 2020-12-23 09:30 UTC by hassenelkamel-exo

2020-12-23 18:35 UTC, ahamdi requested changes
This is a common component, it should be independent from applications usingit. Please pass the full search URL including the project ID

2020-12-24 10:01 UTC, hassenelkamel-exo commented
> This is a common component, it should be independent from applications usingit. Please pass the full search URL including the project ID

2020-12-25 15:51 UTC, ahamdi requested changes

2020-12-25 15:51 UTC, ahamdi commented on webapp/portlet/src/main/webapp/common/js/SuggesterService.js
>    }
Could we let it have other olptions like this ? WDYT ?

```suggestion
  if (searchOptions) {
    if(searchOptions.searchUrl) {
      url = searchOptions.searchUrl;
      delete searchOptions.searchUrl;
    } else {
      url = '/portal/rest/social/people/suggest.json?';
    }
    Object.assign(options, searchOptions);
    params = $.param(options);
    url = url.concat(params);
  }
```

2020-12-25 16:42 UTC, ahamdi approved these changes
LGTM

2020-12-25 17:01 UTC, merged