Task-37851: Integrate the DLP keywords file via UI
Meeds-io/social pull request #508
Opened 2021-01-25 09:59 UTC by AzmiTouil

2021-01-25 10:43 UTC, rdenarie requested changes

2021-01-25 10:43 UTC, rdenarie commented on webapp/portlet/src/main/resources/locale/portlet/dlpQuarantine/dlpQuarantine_en.properties
>  documents.dlp.button.ok=OK
Please updates items keys : it is not documents.dlp.xxx, but items.dlp.xxx

2021-01-25 10:57 UTC, rdenarie approved these changes

2021-01-26 09:06 UTC, rdenarie approved these changes, later dismissed

2021-01-27 14:58 UTC, rdenarie approved these changes, later dismissed

2021-01-28 13:28 UTC, rdenarie approved these changes, later dismissed

2021-01-29 15:02 UTC, ahmadmido approved these changes
LGTM

2021-01-29 15:04 UTC, merged