MAINT-27712: Make sure to be able to mention users when editing a post.
Meeds-io/social pull request #577
Opened 2021-02-22 10:10 UTC by mzorai

The problem comes from the already initialized CKEditor instance, i made sure to reinitialize it when editing a post.

2021-02-22 13:12 UTC, ahamdi requested changes, later dismissed
Do not merge until we fix the inifinite loading isue when editing a post

2021-02-23 17:11 UTC, boubaker approved these changes

2021-02-23 17:43 UTC, ahamdi approved these changes

2021-02-23 18:15 UTC, ahamdi approved these changes

2021-02-23 18:15 UTC, merged