Task-41419: Implement trendMicro malware detection connector
Meeds-io/social pull request #633
Opened 2021-03-17 15:52 UTC by azayati

* This PR implements trendMicro malware detection connector, this connector is defined via the configuration as default MalwareDetectionConnector with the property exo.malwareDetection.connector.trendMicro.isDefault=true 
* In order to call trendMicro API we need these properties:
** exo.malwareDetection.connector.trendMicro.api.host=
exo.malwareDetection.connector.trendMicro.api.userName=
exo.malwareDetection.connector.trendMicro.api.password=
#The same as the MalwareDetectionJob period in ms
exo.malwareDetection.connector.trendMicro.api.listEvents.period=

2021-03-22 09:06 UTC, rdenarie requested changes

2021-03-22 09:06 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +        LOGGER.error("Error when trying to login trendMicro with host={} and userName={}", trendmicroHost, trendmicroUserName, e);
Should we use log format with service={} operation={} and status=ko ?

2021-03-22 09:06 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +        LOGGER.error("Error when trying to get trendmicro events list with host={} and sID={}", trendmicroHost, sid, e);
Should we use log format with service={} operation={} and status=ko

2021-03-22 09:06 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +        LOGGER.error("Error when trying to logout trendMicro with host={} and sID={}", trendmicroHost, sid, e);
Should we use log format with service={} operation={} and status=ko

2021-03-31 07:41 UTC, rdenarie requested changes

2021-03-31 07:41 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/MalwareDetectionFilesConnector.java
> +      LOGGER.error("service={} operation={} parameters=\"fileChecksum:{}\" status=ko duration_ms={} error_msg=Error when trying to get the infected items:{}",
```suggestion
      LOGGER.error("service={} operation={} parameters=\"fileChecksum:{}\" status=ko duration_ms={} error_msg=\"Error when trying to get the infected items:{}\"",
```
https://community.exoplatform.com/portal/g/:spaces:exo_itop/exo_itop/wiki/SPEC_-_logging_for_monitoring

2021-03-31 08:22 UTC, azayati commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/MalwareDetectionFilesConnector.java
> +      LOGGER.error("service={} operation={} parameters=\"fileChecksum:{}\" status=ko duration_ms={} error_msg=Error when trying to get the infected items:{}",
updated

2021-03-31 08:58 UTC, rdenarie requested changes

2021-03-31 08:58 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +        LOGGER.error("remote_service={} operation={} parameters=\"host:{}\" \"userName:{}\" status=ko duration_ms={} error_msg=\"Error when trying to login trendMicro\"",
should we put response code in error message ?

2021-03-31 08:58 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +        LOGGER.error("remote_service={} operation={} parameters=\"host:{}\" \"sID:{}\" status=ko duration_ms={} error_msg=\"Error when trying to get trendmicro events list\"",
should we put reponse code in error message

2021-03-31 08:58 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/service/malwareDetection/connector/TrendMicroMalwareDetectionConnector.java
> +          LOGGER.error("remote_service={} operation={} parameters=\"host:{}\" \"sID:{}\" status=ko duration_ms={} error_msg=\"Error when trying to logout trendMicro\"",
should we put response code in error message

2021-03-31 09:36 UTC, rdenarie approved these changes

2021-03-31 09:51 UTC, merged