Task-41285: Implement drawer for users advanced filter in userManagement
Meeds-io/social pull request #658
Opened 2021-03-30 11:15 UTC by AzmiTouil

2021-03-30 20:17 UTC, plamarque commented on webapp/portlet/src/main/resources/locale/portlet/Portlets_en.properties
> +UsersManagement.lastConnexion.connected=Connected
« connection » in english. not connexion

2021-04-02 14:49 UTC, rdenarie requested changes
Add a unit test to UserRestResroucesV1.getUsers : be sure that if you call without userType, you get the list of internal users without error

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSIdentityStorageImpl.java
>                                        boolean IsEnabled,
```suggestion
                                      boolean isEnabled,
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/RDBMSIdentityStorageImpl.java
> +    List<String> usernames = getIdentityDAO().getAllIdsByProviderSorted(providerId, firstCharacterFieldName, firstCharacter, sortField, sortDirection, IsEnabled, userType, offset, limit);
```suggestion
    List<String> usernames = getIdentityDAO().getAllIdsByProviderSorted(providerId, firstCharacterFieldName, firstCharacter, sortField, sortDirection, isEnabled, userType, offset, limit);
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +  public List<String> getAllIdsByProviderSorted(String providerId, String firstCharacterFieldName, char firstCharacter, String sortField, String sortDirection, boolean IsEnabled, String userType, lon
```suggestion
  public List<String> getAllIdsByProviderSorted(String providerId, String firstCharacterFieldName, char firstCharacter, String sortField, String sortDirection, boolean isEnabled, String userType, long offset, long limit) {
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +    Query query = getIdentitiesQuerySortedByField(providerId, firstCharacterFieldName, firstCharacter, sortField, sortDirection, IsEnabled, userType);
```suggestion
    Query query = getIdentitiesQuerySortedByField(providerId, firstCharacterFieldName, firstCharacter, sortField, sortDirection, isEnabled, userType);
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +  public int getAllIdsCountByProvider(String providerId, String userType, boolean IsEnabled) {
```suggestion
  public int getAllIdsCountByProvider(String providerId, String userType, boolean isEnabled) {
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +    Query query = getIdentitiesQueryCount(providerId, userType, IsEnabled);
```suggestion
    Query query = getIdentitiesQueryCount(providerId, userType, isEnabled);
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +                                                boolean IsEnabled,
```suggestion
                                                boolean isEnabled,
```

2021-04-02 14:49 UTC, rdenarie commented on component/core/src/main/java/org/exoplatform/social/core/jpa/storage/dao/jpa/IdentityDAOImpl.java
> +  private Query getIdentitiesQueryCount(String providerId, String userType, boolean IsEnabled) {
```suggestion
  private Query getIdentitiesQueryCount(String providerId, String userType, boolean isEnabled) {
```

2021-04-02 14:49 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/rest/impl/user/UserRestResourcesV1.java
> +    if (!userACL.getSuperUser().equals(userId) && !RestUtils.isMemberOfAdminGroup() && !userType.equals(INTERNAL)) {
```suggestion
    if (!userACL.getSuperUser().equals(userId) && !RestUtils.isMemberOfAdminGroup() && userType!=null && !userType.equals(INTERNAL)) {
```

2021-04-02 14:49 UTC, rdenarie commented on component/service/src/main/java/org/exoplatform/social/rest/impl/user/UserRestResourcesV1.java
> +                           @ApiParam(value = "User type to filter, ex: internal, external", required = false) @QueryParam("userType") String userType,
add a defualt value for userType ("internal")

2021-04-02 14:49 UTC, rdenarie commented on webapp/portlet/src/main/webapp/people-list/components/PeopleCardList.vue
> +        searchUsersFunction = this.$userService.getUsers(this.keyword, this.offset, this.limitToFetch + 1, this.fieldsToRetrieve, this.userType);
remove this modification

2021-04-06 07:26 UTC, rdenarie approved these changes

2021-04-07 11:50 UTC, merged