Fix the backport of MAINT-38140
Meeds-io/social pull request #768
Opened 2021-06-10 14:40 UTC by hakermi

2021-06-10 15:13 UTC, plamarque commented on component/core/src/main/java/org/exoplatform/social/core/jpa/search/ProfileSearchConnector.java
> +        continue;
I think this is swallowing information when some data retrieved from ES is not wellformed (userName expected, but not in the result). Shouldn't we log (log.warn if unexpected,  log.debug() if it's common and) the fact ?  
ex: "WARN : ES hit $HIT contained invalid userName information $USER and was ignored"

2021-06-11 19:10 UTC, ahamdi requested changes

2021-06-11 19:10 UTC, ahamdi commented on component/core/src/main/java/org/exoplatform/social/core/jpa/search/ProfileSearchConnector.java
> +      Profile profile = getIdentityProfile(userName);
We are getting information from ES, no need to reload the profile from storage

2021-06-11 19:10 UTC, ahamdi commented on component/core/src/main/java/org/exoplatform/social/core/jpa/search/ProfileSearchConnector.java
> +      if (profile == null) {
@hakermi This should not b e a normal case, do you have a steps to reproduce such a behaviour ?

2021-07-07 11:05 UTC, closed without merging