Task-45373: Fix Applications' name and description are not displayed by their value in space settings interface
Meeds-io/social pull request #775
Opened 2021-06-11 14:20 UTC by NaderSai

Problem: the name and the description of apps were not displayed by their values in the addApplication drawer.
How it was solved: delete the duplicated values, already read from the SpaceSettingApplicationCard component, from the SpaceSettingAddApplicationDrawer component.

2021-07-22 15:21 UTC, ahamdi requested changes
This will break the intyernationalization of th edescription and title keys of all applications. Please make sure that the fix will work and display correctly each application's title and description

2021-07-27 21:26 UTC, NaderSai commented
> This will break the intyernationalization of th edescription and title keys of all applications. Please make sure that the fix will work and display correctly each application's title and description
the content of apps is charged from the SpaceSettingApplicationCard in which the internationalization is respected. i verified that and it works.

2021-07-28 08:46 UTC, ahamdi approved these changes, later dismissed

2021-07-28 12:00 UTC, ahamdi approved these changes

2021-07-28 12:00 UTC, merged