US-InsertVideo-02 : Video links preview after posting
Meeds-io/social pull request #88
Opened 2020-05-07 13:46 UTC by Rdidmohamedelhadi

2020-05-12 13:15 UTC, thomasdelhomenie requested changes

2020-05-12 13:15 UTC, thomasdelhomenie commented on component/service/src/main/java/org/exoplatform/social/processor/EmbedProcessor.java
> +  private static final String HTML_PARAM = "html";
```suggestion
  private static final String MEDIA_HTML = "media_html";
```
I would rename it like that to make it more meaningful. WDYT ?

2020-05-14 07:06 UTC, thomasdelhomenie submitted a review, later dismissed

2020-05-14 09:44 UTC, rdenarie approved these changes
LGTM

2020-05-14 10:44 UTC, merged